/*
 * generated by Xtext
 */
package famix;

import org.eclipse.xtext.naming.IQualifiedNameProvider;

import famix.scoping.M3xNameProvider;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class M3xRuntimeModule extends famix.AbstractM3xRuntimeModule {
	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		// TODO Auto-generated method stub
		return M3xNameProvider.class;
	}

}
