/*
* generated by Xtext
*/
package famix;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class M3xStandaloneSetup extends M3xStandaloneSetupGenerated{

	public static void doSetup() {
		new M3xStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

